root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/nakama"
  cmd = "go tool templ generate --log-level error && go build -o ./tmp/nakama ./cmd/nakama"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = [".*_test.go", ".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "sql", "templ", "css", "js", "env"]
  include_file = []
  kill_delay = "0s"
  log = "air.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = true
  silent = true
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 4000
  enabled = true
  proxy_port = 4001

[screen]
  clear_on_rebuild = false
  keep_scroll = true
