# Config file for [Air](https://github.com/cosmtrek/air)

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/nakama"
  cmd = "go build -o ./tmp/nakama ./cmd/nakama"
  delay = 0
  exclude_dir = ["bin", "tmp", "testdata", "cockroach-data", "minio-data", "node_modules"]
  exclude_file = []
  exclude_regex = ["_test\\.go"]
  exclude_unchanged = true
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tmpl", "sql", "html", "css", "js"]
  include_file = []
  kill_delay = "0s"
  log = "air.log"
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = true
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
