// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package nakama

import (
	"time"
)

type Post struct {
	ID        string
	UserID    string
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        string
	Email     string
	Username  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
