# This file is VSCode specific
# you must have "humao.rest-client" extension installed.

@host = http://localhost:3000

POST {{host}}/api/users
Content-Type: application/json

{
    "email": "test@example.org",
    "username": "test"
}

###
# @name login
POST {{host}}/api/dev_login
Content-Type: application/json

{
    "email": "john@example.org"
}

###
POST {{host}}/api/send_magic_link
Content-Type: application/json

{
    "email": "john@example.org",
    "redirectURI": "http://localhost:3000/auth_redirect"
}

###
GET {{host}}/api/auth_user
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/api/token
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/api/users?search=&first=&after=
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/api/usernames?starting_with=&first=&after=
# Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/api/users/john
Authorization: Bearer {{login.response.body.token}}

###
PUT {{host}}/api/auth_user/avatar
Authorization: Bearer {{login.response.body.token}}
Content-Type: image/png

< assets/sample_avatar.png

###
POST {{host}}/api/users/jane/toggle_follow
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/api/users/john/followers?first=&after=
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/api/users/john/followees?first=&after=
Authorization: Bearer {{login.response.body.token}}

###
# @name createPost
POST {{host}}/api/posts
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
    "content": "new post"
}

###
GET {{host}}/api/users/john/posts?last=&before=
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/api/posts/{{createPost.response.body.id}}
Authorization: Bearer {{login.response.body.token}}

###
POST {{host}}/api/posts/{{createPost.response.body.id}}/toggle_like
Authorization: Bearer {{login.response.body.token}}

###
POST {{host}}/api/posts/{{createPost.response.body.id}}/toggle_subscription
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/api/timeline?last=&before=
Authorization: Bearer {{login.response.body.token}}

###
# @name createComment
POST {{host}}/api/posts/{{createPost.response.body.id}}/comments
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
    "content": "new comment"
}

###
GET {{host}}/api/posts/{{createPost.response.body.id}}/comments?last=&before=
Authorization: Bearer {{login.response.body.token}}

###
POST {{host}}/api/comments/{{createComment.response.body.id}}/toggle_like
Authorization: Bearer {{login.response.body.token}}

###
# @name notifications
GET {{host}}/api/notifications?last=&before=
Authorization: Bearer {{login.response.body.token}}

###
GET {{host}}/api/has_unread_notifications
Authorization: Bearer {{login.response.body.token}}

###
POST {{host}}/api/notifications/{{notifications.response.body[0].id}}/mark_as_read
Authorization: Bearer {{login.response.body.token}}

###
POST {{host}}/api/mark_notifications_as_read
Authorization: Bearer {{login.response.body.token}}
