package nakama

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"github.com/lib/pq"
	"github.com/nakamauwu/nakama/db"
)

type sqlInsertTimelineItem struct {
	UserID string
	PostID string
}

type sqlInsertPost struct {
	UserID  string
	Content string
}

type sqlInsertTimeline struct {
	PostID     string
	FollowedID string
}

type sqlSelectPosts struct {
	AuthUserID string
	Username   string
}

type sqlUpdatePost struct {
	PostID                  string
	IncreaseCommentsCountBy int32
	ReactionsCount          *ReactionsCount
}

type sqlSelectPost struct {
	PostID     string
	AuthUserID string
}

type sqlInsertedTimelineItem struct {
	ID     string
	UserID string
}

func (svc *Service) sqlInsertPost(ctx context.Context, in sqlInsertPost) (CreatedPost, error) {
	var out CreatedPost

	const query = `
		INSERT INTO posts (id, user_id, content)
		VALUES ($1, $2, $3)
		RETURNING created_at
	`
	postID := genID()
	err := svc.DB.QueryRowContext(ctx, query, postID, in.UserID, in.Content).Scan(&out.CreatedAt)
	if err != nil {
		return out, fmt.Errorf("sql insert post: %w", err)
	}

	out.ID = postID

	return out, nil
}

func (svc *Service) sqlInsertTimelineItem(ctx context.Context, in sqlInsertTimelineItem) (string, error) {
	const query = `
		INSERT INTO timeline (user_id, post_id)
		VALUES ($1, $2)
		RETURNING id
	`
	var id string
	err := svc.DB.QueryRowContext(ctx, query, in.UserID, in.PostID).Scan(&id)
	if err != nil {
		return "", fmt.Errorf("sql insert timeline item: %w", err)
	}

	return id, nil
}

func (svc *Service) sqlInsertTimeline(ctx context.Context, in sqlInsertTimeline) ([]sqlInsertedTimelineItem, error) {
	const query = `
		INSERT INTO timeline (user_id, post_id)
		SELECT user_follows.follower_id, $1
		FROM user_follows
		WHERE user_follows.followed_id = $2
		ON CONFLICT (user_id, post_id) DO NOTHING
		-- timeline id is autogenerated by the database using ulid.
		RETURNING id, user_id
	`

	rows, err := svc.DB.QueryContext(ctx, query, in.PostID, in.FollowedID)
	if err != nil {
		return nil, fmt.Errorf("sql fanout timeline: %w", err)
	}

	return db.Collect(rows, func(scan db.ScanFunc) (sqlInsertedTimelineItem, error) {
		var out sqlInsertedTimelineItem
		return out, scan(&out.ID, &out.UserID)
	})
}

func (svc *Service) sqlSelectPosts(ctx context.Context, in sqlSelectPosts) ([]Post, error) {
	const query = `
		SELECT
			  posts.id
			, posts.user_id
			, posts.content
			, posts.reactions_count
			, reactions
			, posts.comments_count
			, posts.created_at
			, posts.updated_at
			, users.username
			, users.avatar_path
			, users.avatar_width
			, users.avatar_height
		FROM posts
		INNER JOIN users ON posts.user_id = users.id
		LEFT JOIN (
			SELECT post_id, array_agg(reaction) AS reactions
			FROM post_reactions
			WHERE post_reactions.user_id = $1
			GROUP BY post_id
		) AS post_reactions ON post_reactions.post_id = posts.id
		WHERE
			CASE
				WHEN $2::varchar != '' THEN LOWER(users.username) = LOWER($2::varchar)
				ELSE true
			END
		ORDER BY posts.id DESC
	`
	rows, err := svc.DB.QueryContext(ctx, query, in.AuthUserID, in.Username)
	if err != nil {
		return nil, fmt.Errorf("sql select posts: %w", err)
	}

	return db.Collect(rows, func(scan db.ScanFunc) (Post, error) {
		var out Post
		var reactions []string
		err := scan(
			&out.ID,
			&out.UserID,
			&out.Content,
			&db.JSONValue{Dst: &out.ReactionsCount},
			pq.Array(&reactions),
			&out.CommentsCount,
			&out.CreatedAt,
			&out.UpdatedAt,
			&out.User.Username,
			svc.sqlScanAvatar(&out.User.AvatarPath),
			&out.User.AvatarWidth,
			&out.User.AvatarHeight,
		)
		if err != nil {
			return out, err
		}

		out.ReactionsCount.Apply(reactions)

		return out, nil
	})
}

func (svc *Service) sqlSelectTimeline(ctx context.Context, userID string) ([]Post, error) {
	const query = `
		SELECT
			  posts.id
			, posts.user_id
			, posts.content
			, posts.reactions_count
			, reactions
			, posts.comments_count
			, posts.created_at
			, posts.updated_at
			, users.username
			, users.avatar_path
			, users.avatar_width
			, users.avatar_height
		FROM timeline
		INNER JOIN posts ON timeline.post_id = posts.id
		INNER JOIN users ON posts.user_id = users.id
		LEFT JOIN (
			SELECT post_id, array_agg(reaction) AS reactions
			FROM post_reactions
			WHERE post_reactions.user_id = $1
			GROUP BY post_id
		) AS post_reactions ON post_reactions.post_id = posts.id
		WHERE timeline.user_id = $1
		ORDER BY timeline.id DESC
	`
	rows, err := svc.DB.QueryContext(ctx, query, userID)
	if err != nil {
		return nil, fmt.Errorf("sql select timeline: %w", err)
	}

	return db.Collect(rows, func(scan db.ScanFunc) (Post, error) {
		var out Post
		var reactions []string
		err := scan(
			&out.ID,
			&out.UserID,
			&out.Content,
			&db.JSONValue{Dst: &out.ReactionsCount},
			pq.Array(&reactions),
			&out.CommentsCount,
			&out.CreatedAt,
			&out.UpdatedAt,
			&out.User.Username,
			svc.sqlScanAvatar(&out.User.AvatarPath),
			&out.User.AvatarWidth,
			&out.User.AvatarHeight,
		)
		if err != nil {
			return out, err
		}

		out.ReactionsCount.Apply(reactions)

		return out, nil
	})
}

func (svc *Service) sqlSelectPost(ctx context.Context, in sqlSelectPost) (Post, error) {
	const query = `
		SELECT
			  posts.id
			, posts.user_id
			, posts.content
			, posts.reactions_count
			, reactions
			, posts.comments_count
			, posts.created_at
			, posts.updated_at
			, users.username
			, users.avatar_path
			, users.avatar_width
			, users.avatar_height
		FROM posts
		INNER JOIN users ON posts.user_id = users.id
		LEFT JOIN (
			SELECT post_id, array_agg(reaction) AS reactions
			FROM post_reactions
			WHERE post_reactions.user_id = $1
			GROUP BY post_id
		) AS post_reactions ON post_reactions.post_id = posts.id
		WHERE posts.id = $2
	`
	var p Post
	var reactions []string
	err := svc.DB.QueryRowContext(ctx, query, in.AuthUserID, in.PostID).Scan(
		&p.ID,
		&p.UserID,
		&p.Content,
		&db.JSONValue{Dst: &p.ReactionsCount},
		pq.Array(&reactions),
		&p.CommentsCount,
		&p.CreatedAt,
		&p.UpdatedAt,
		&p.User.Username,
		svc.sqlScanAvatar(&p.User.AvatarPath),
		&p.User.AvatarWidth,
		&p.User.AvatarHeight,
	)
	if errors.Is(err, sql.ErrNoRows) {
		return Post{}, ErrPostNotFound
	}

	if err != nil {
		return Post{}, fmt.Errorf("sql select post: %w", err)
	}

	p.ReactionsCount.Apply(reactions)

	return p, nil
}

func (svc *Service) sqlSelectPostReactionsCount(ctx context.Context, postID string) (ReactionsCount, error) {
	const query = `
		SELECT reactions_count FROM posts WHERE id = $1
	`

	var out ReactionsCount
	row := svc.DB.QueryRowContext(ctx, query, postID)
	err := row.Scan(&db.JSONValue{Dst: &out})
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrPostNotFound
	}

	if err != nil {
		return nil, fmt.Errorf("sql select post reactions count: %w", err)
	}

	return out, nil
}

func (svc *Service) sqlUpdatePost(ctx context.Context, in sqlUpdatePost) (time.Time, error) {
	const query = `
		UPDATE posts
		SET comments_count = comments_count + $1
			, reactions_count = COALESCE($2, reactions_count)
			, updated_at = now()
		WHERE id = $3
		RETURNING updated_at
	`
	var updatedAt time.Time
	row := svc.DB.QueryRowContext(ctx, query,
		in.IncreaseCommentsCountBy,
		db.JSONValue{Dst: in.ReactionsCount},
		in.PostID,
	)
	err := row.Scan(&updatedAt)
	if err != nil {
		return time.Time{}, fmt.Errorf("sql update post: %w", err)
	}

	return updatedAt, nil
}
